import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Оғир"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          10.03.2025й куни соат 02-00ларда “Қуюв-механика заводи” АЖ темирчилик ва пресслаш цехининг қўлда ишлов берувчи темирчиси Марифжанов Хасан Толибжон ўғли (2004 йил 11 март куни Тошкент вилояти Ўртачирчик туманида туғилган, маълумоти ўрта, темир йўлда иш стажи 2023 йилдан, уйланмаган) билан оқибати оғир бўлган бахтсиз ҳодиса содир бўлган. Темирчилик ва пресслаш цехининг қўлда ишлов берувчи темирчиси Марифжанов Хасан (МН-1000) да кўприк таянч ўқини болғалашда детал унинг оёғига тушиб кетиб, чап оёғининг тўпиғига юқорисидан жароҳат олган. Корхона тиббий пунктида биринчи ёрдам кўрсатилиб, Республика шошилинч тиббий ёрдам илмий маркази Тошкент вилояти филиалига олиб борилган. Шифокорлар томонидан чап катта болдир суягини пастки учлигидан, ташқи тўпиғидан ёпиқ синиши ташчиси қўйилган.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
