import Head from 'next/head';
import React from 'react';
import Hero7 from '../components/Hero/Hero7';
import Layout from '../components/Layout';

export default function CaseStudyShowcase() {
  const heroSocialLinks = [
    // {
    //   name: 'Behance',
    //   links: '/',
    // },
    // {
    //   name: 'Twitter',
    //   links: '/',
    // },
  ];

  const showcaseData = [
    {
      title: '	1.Оғир <br/>',
      imgUrl: 'https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg',
      href: '/case-study-details',
    },
    {
      title: '2.Ўрта Оғир<br/>',
      imgUrl: 'https://kartinki.pics/pics/uploads/posts/2022-08/thumbs/1661167847_52-kartinkin-net-p-zheleznaya-doroga-oboi-krasivo-68.jpg',
      href: '/case-study-details1',
    },
    {
      title: '3.Оғир <br />',
      imgUrl: 'https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_derevia_solnechnyj_svet_903684_1920x1080.jpg',
      href: '/case-study-details2',
    },
    {
      title: '4.Оғир бўлмган<br />',
      imgUrl: 'https://images.wallpaperscraft.ru/image/single/stolby_fonari_derevia_891332_1920x1080.jpg',
      href: '/case-study-details3',
    },
    {
      title: '5.Ўрта оғир<br />',
      imgUrl: 'https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_fonari_svet_913138_1920x1080.jpg',
      href: '/case-study-details4',
    },
    {
      title: ' 6.Оғир <br />',
      imgUrl: 'https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_fonari_svet_913138_1920x1080.jpg',
      href: '/case-study-details5',
    },
    {
      title: '7.Ўлим<br />',
      imgUrl: 'https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_fonari_svet_913138_1920x1080.jpg',
      href: '/case-study-details6',
    },
   
  ];
  return (
    <>
      <Head>
        <title>Home - Case Study Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero7
          heroSocialLinks={heroSocialLinks}
          // socialLinksHeading="Follow Us"
          showcaseData={showcaseData}
        />
      </Layout>
    </>
  );
}
