import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Ўрта бўғин раҳбарлари-нинг ўз вазифасига масъулиятсиз-лиги ва технологик жараён талаблари риоя этмаслик"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          19.01.2025й куни Қўнғирот МТУ га қарашли ПМС-279 корхонаси йўл созловчиси Абдуллаев мансур Абдурамонович (14.01.1976 йил Қарақалпоғистон Рес. Қўнғирот туманида туғилган, маълумоти ўрта, оилали 2 нафар фарзанди бор, темир йўлдаги иш стажи 1996 йилдан) билан оқибати ўрта-оғир бўлган бахтсиз ҳодиса содир бўлган.
19.01.2025 йил куни ПМС-279 корхонаси ходимлари Мискен-Тўрткўл оралиғининг 515 кмда УК-25/9-18 русумли темир йўл крани ёрдамида релсларни платформага йиғиш вақтида тахминан 11-20 ларда йўл созловчи М.А.Абдуллаев релсни қисиш чангалини ажратиб, релсни платформа вагонига тахлаш жараёнида реслни лом билан сурган вақти релс чап оёғига йиқилиши натижасида 1 ва 2-бармоғи синиши жароҳатини олган. М.А.Абдуллаевга биринчи тиббий ёрдам кўрсатилиб Тўрткўл ш. шифохонасига ётқизилган.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
