import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Ўрта оғир"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          17-18.04.2025йил кечаси соат 02-08да тунги навбатчиликда ишлаёгган ВЧД-7 Зиёвуддин маскани вагон кўрувчиси Бегматов Голибжон Шавкатович (Самарканд вил, Пахтачи тум. 1997 йнл 09 майда туғилган, оилили 1 нафар фарзанди бор, маълумоти ўрта-махсус, темир йўлда иш стажи 2016 йилдан) билан оқибати ўлим билан тугаган бахтсиз ходиса содир булган. 
17-18 апрел куни тахминан тунги соат 02-08 лар атрофида тунги навбатчиликда ишлаётган вагон кўрувчилари Ғ.Ш.Бегматов ва Э.К.Кудратов билан биргаликда ст.Зиёвуддин навбатчиси С.К.Норбоевнинг баланд товушли радио алоқа орқали жуфт 3004-сонли юк поезди 2-йўлдан ўтиб кетиши ҳақида берган хабаридан сўнг, 3004-сонли юк поезди 1001-электровоз машинист Холиковни соат 02-08 да икки томондан кузатган. Вагон кўрувчи Е.Ш.Бегмагов жуфт поездни кузатаётганда бир вактда 1-бўш бош йўлдан ўтиб кетаётган 123-созли 0106-электровоз машинист Нормуродов бошкарувидаги Волгаград-Тошкент йўловчи поезди 3854км ПК-3да вагон кўрувчи Б.Г.Бегматовни уриб кетиши оқибатида воқеа жойида вафот этган.

          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
