import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Ўрта бўғин раҳбарлари-нинг ўз вазифасига масъулиятсиз-лиги, Электр хавфсизлиги ва технологик жараён талабларига риоя этмаслик"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          16.02.2025й куни соат 15-00 ларда Андижон вагон депосининг йиғув цехи чилангари Эргашев Элмурод Рўзибой ўғли (1996 йил 22 январда Андижон вилояти, Андижон шахрида туғилган, оилали, маълумоти ўрта махсус, темир йўлда иш стажи 2022 йилдан) билан оқибати оғир бўлмаган бахтсиз ходиса содир бўлган.
16.02.2025й куни соат 15-00ларда Андижон вагон депосининг йиғув цехи чилангари Эргашев Элмурод Рўзибой ўғли депонинг 2-темир йўлида таъмирланаётган №67140319 рақамли ярим очиқ вагоннинг таъмирланган юк тушуриш қопқоғини вагонга илиш жараёнида қопқоқни илиш мосламаси тушиб кетиши натижасида Э.Эргашевнинг ўнг оёқ бармоқлари жарохат олган. Шифохона томонидан Э.Эргашевнинг ўнг оёғи 1,2,3,4-бармоқларидан оғир бўлмаган жарохатини олганлиги тўғрисида хулоса берилган.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
