import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Ўзининг эҳтиётсизлиги ва технологик жараён талаблари риоя этмаслик"
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          18.01.2025й куни Тошкент МТУ га қарашли Даштобод-Робот станциялари оралиғида Зарбдор станцияси бош кондуктори Қўшназаров Дилмурод Мавлон ўғли (07.12.1994 йил Жиззах вил. Зарбдор тум. туғилган, маълумоти ўрта махсус, оилали 2 нафар фарзанди бор, темир йўлдаги иш стажи 2013 йилдан) билан оқибати оғир бахтсиз ҳодиса содир бўлган.
18.01.2025 йил куни соат 13:00 дан 15:00 гача ПЧ-Жиззах талабига асосан Даштабод-Работ станциялари оралиғида улоқсиз релсларни тушириш ишлари режалаштирилган бўлиб, ушбу ишларни бажариб қайтаётганда,  тахминан соат 14:50 лар атрофида 8401-сонли ишчи поезди Даштобод станциясига кириб келиб тўхтаган ва орқага ҳаракатланган, натижада 42 та вагондан иборат ишчи поезди охирги платформа вагони устида ўтирган Зарбдор станцияси бош кондуктори Д.Қўшназаров силтаниш оқибатида вагон устидан темир йўл излари орасига йиқилиб ўнг оёғи бош бармоғи ҳамда иккинчи бармоғи вагон ғилдиркалари остида қолиб эзилиб шикастланган. 

          </p>
        </Div>
      </Layout>
    </>
  );
}
