import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
  return (
    <>
      <Head>
        <title>Case Study Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Меҳнат муҳофазаси ва техника хавфсизлиги
          қоидаларига риоя қилмаслик ва ўзининг эҳтиётсизли-ги  
          "
          bgSrc="https://images.wallpaperscraft.ru/image/single/zheleznaia_doroga_relsy_rassvet_1217626_1920x1080.jpg"
          pageLinkText="Case Study Details"
        />
        {/* <Spacing lg="120" md="80" /> */}
        <Div className="container">
          <Spacing lg="90" md="45" />
          <p className="cs-m0">
          21.01.2025й куни соат 15:00 лар атрофида ПЧ-Жиззах 12-околодка трактор ҳайдовчиси Ниятов Умрзоқ Чулиевич (07.02.1966 й Жиззах в. Фориш тум. туғилган, оилали, 4 нафар фарзанди бор, темир йўлдаги иш стажи 2006 йилдан) билан бахтсиз ҳодиса содир бўлган.
21.01.2025 йил куни эрталаб 07:00 да жорий йўл-йўриқ бригадири С.А.Абдуқодиров томонидан ўтказилган. Давлат рақами 25 557АА ва тиркама рақами 25 110АА Т-28Х4 тракторини эрталабги техник кўрикда ҳайдовчи тиркаманинг орқа шинаси босими пастлигини аниқланган. Шина босимини меъёрга келтириш мақсадида йўл устаси О.Қ.Сувонқуловдан рухсат олиб Эгизбулоқ ҚФЙ ҳудудида жойлашган шина таъмирлаш устахонасига бориб қайтаётганда бошқарувни йўқотиган ва йўлдан чиқиб кетиб ағдарилиши натижасида бахтсиз ҳодиса содир бўлган.
          </p>
        </Div>
        <Div className="container">
          {/* <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          /> */}
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
